---
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/bundle/**/*'
    - 'test/dummy/**/*'
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'lib/active_record/embedded/model.rb'
    - 'test/test_helper.rb'

Metrics/AbcSize:
  Max: 39

Metrics/BlockLength:
  CountComments: false
  ExcludedMethods:
    - class_methods
    - refine
  Max: 36

# Metrics/MethodLength:
#   CountComments: false
#   Max: 18

Metrics/ModuleLength:
  CountComments: false
  Max: 180

Metrics/ParameterLists:
  Max: 6

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'lib/active_record/embedded/model.rb'

Style/DoubleNegation:
  Exclude:
    - 'lib/active_record/embedded/field/boolean.rb'
