version: '3'
services:
  mysql:
    image: mysql:alpine
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=foo
  postgresql:
    image: postgres:alpine
    ports:
      - 5432:5432
