name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby_version: 2.6.x
      - run: docker-compose up -d
      - run: |
          sudo apt update
          sudo apt install -y libmysqlclient-dev postgresql-client
          bundle install
      - run: bundle install
      - run: bundle exec rake
